export const CORES = [
  'Branco',
  'Preto',
  'Prata',
  'Cinza',
  'Vermelho',
  'Azul',
  'Verde',
  'Amarelo',
  'Marrom',
  'Laranja',
  'Bordô',
  'Dourado',
  'Outro',
]

export const CARACTERISTICAS = [
  'Único Dono',
  'IPVA Pago',
  'Licenciado',
  'Garantia de Fábrica',
  'Revisões na Concessionária',
  'Aceita Troca',
  'Alienado',
  'Colecionador',
  'Veículo de Teste',
]

export const OPCIONAIS = [
  'Airbag',
  'Alarme',
  'Ar condicionado',
  'Ar quente',
  'Banco com regulagem de altura',
  'Bancos em couro',
  'Capota marítima',
  'CD e MP3 Player',
  'CD Player',
  'Computador de bordo',
  'Controle automático de velocidade',
  'Controle de tração',
  'Desembaçador traseiro',
  'Direção hidráulica',
  'DVD Player',
  'Encosto de cabeça traseiro',
  'Farol de xenônio',
  'Freio ABS',
  'GPS',
  'Limpador traseiro',
  'Protetor de caçamba',
  'Rádio',
  'Rádio e toca fitas',
  'Retrovisor fotocrômico',
  'Retrovisores elétricos',
  'Rodas de liga leve',
  'Sensor de chuva',
  'Sensor de estacionamento',
  'Teto solar',
  'Tração 4x4',
  'Travas elétricas',
  'Vidros elétricos',
  'Volante com regulagem de altura',
  'Câmera de Ré',
  'Central Multimídia',
  'Bluetooth',
  'Entrada USB',
  'Farol de Neblina',
  'Comando de Áudio e Telefone no Volante',
  'Direção Elétrica',
  'Controle de Estabilidade',
  'Assistente de Partida em Rampa',
  'Kit Multimídia',
  'Piloto Automático',
  'Sensor de Farol',
  'Partida Start/Stop',
  'Alerta de Ponto Cego',
  'Alerta de Mudança de Faixa',
]
