export const CARACTERISTICAS = [
  'Adaptado para Def. Físico',
  'Único Dono',
  'Blindado',
  'Chave Reserva',
  'Garantia de Fábrica',
  'IPVA Pago',
  'Licenciado',
  'Manual do Proprietário',
  'Passou por Leilão',
  'Revisado em Concessionária',
]

export const OPCIONAIS = [
  'Airbag Motorista',
  'Airbag Passageiro',
  'Airbag Laterais',
  'Freios ABS',
  'Alarme',
  'Tração 4x4',
  'Ar Condicionado',
  'Ar Condicionado Digital',
  'Banco de Couro',
  'Bancos Aquecidos',
  'Teto Solar',
  'Volante Regulagem de Altura',
  'Desembaçador Traseiro',
  'Banco Motorista Regulagem Altura',
  'Multimídia',
  'GPS',
  'Bluetooth',
  'Entrada USB',
  'Câmera de Ré',
  'Sensor de Estacionamento',
  'Sensor de Chuva',
  'Sensor de Luminosidade',
  'Computador de Bordo',
  'Controle de Som no Volante',
  'Android Auto',
  'Apple CarPlay',
  'DVD Player',
  'CD Player',
  'Rodas de Liga Leve',
  'Insufilm',
  'Retrovisores Elétricos',
  'Retrovisor Fotocrômico',
  'Para-choques na cor do veículo',
  'Faróis de Xenon',
  'Farol de Milha',
  'Limpador Traseiro',
  'Vidros Elétricos',
  'Vidros Elétricos Traseiros',
  'Travas Elétricas',
  'Capota Marítima',
  'Protetor de Caçamba',
  'Porta-Copos',
  'Direção Elétrica',
  'Direção Hidráulica',
  'Controle de Tração',
  'Piloto Automático/Cruise Control',
]

export const CORES = [
  'Preto',
  'Branco',
  'Prata',
  'Cinza',
  'Vermelho',
  'Azul',
  'Verde',
  'Amarelo',
  'Laranja',
  'Bege',
  'Marrom',
  'Rosa',
  'Outro',
]
