// Estimativa de região do lead pelo DDD do telefone (15/09/2026) — leads não
// têm cidade/estado gravados no banco, só `origem` (canal, não localização).
// Isso é aproximado: um DDD cobre uma área, não uma cidade exata, e não pega
// número portado pra outra região. Tabela fixa da ANATEL, não muda.
export const DDD_REGIAO: Record<string, string> = {
  '11': 'SP - Capital/Grande SP',
  '12': 'SP - Vale do Paraíba',
  '13': 'SP - Baixada Santista',
  '14': 'SP - Bauru/Marília',
  '15': 'SP - Sorocaba',
  '16': 'SP - Ribeirão Preto',
  '17': 'SP - São José do Rio Preto',
  '18': 'SP - Presidente Prudente',
  '19': 'SP - Campinas',
  '21': 'RJ - Rio de Janeiro',
  '22': 'RJ - Norte Fluminense',
  '24': 'RJ - Sul Fluminense',
  '27': 'ES - Grande Vitória',
  '28': 'ES - Sul do Espírito Santo',
  '31': 'MG - Belo Horizonte',
  '32': 'MG - Zona da Mata',
  '33': 'MG - Vale do Rio Doce',
  '34': 'MG - Triângulo Mineiro',
  '35': 'MG - Sul de Minas',
  '37': 'MG - Centro-Oeste de Minas',
  '38': 'MG - Norte de Minas',
  '41': 'PR - Curitiba',
  '42': 'PR - Ponta Grossa/Guarapuava',
  '43': 'PR - Londrina',
  '44': 'PR - Maringá',
  '45': 'PR - Cascavel/Foz do Iguaçu',
  '46': 'PR - Francisco Beltrão',
  '47': 'SC - Joinville/Norte',
  '48': 'SC - Florianópolis',
  '49': 'SC - Chapecó/Oeste',
  '51': 'RS - Porto Alegre',
  '53': 'RS - Pelotas',
  '54': 'RS - Caxias do Sul',
  '55': 'RS - Santa Maria/Oeste',
  '61': 'DF - Brasília',
  '62': 'GO - Norte de Goiás',
  '63': 'TO - Tocantins',
  '64': 'GO - Sul de Goiás',
  '65': 'MT - Cuiabá',
  '66': 'MT - Norte do Mato Grosso',
  '67': 'MS - Mato Grosso do Sul',
  '68': 'AC - Acre',
  '69': 'RO - Rondônia',
  '71': 'BA - Salvador',
  '73': 'BA - Sul da Bahia',
  '74': 'BA - Norte/Nordeste da Bahia',
  '75': 'BA - Feira de Santana',
  '77': 'BA - Vitória da Conquista',
  '79': 'SE - Sergipe',
  '81': 'PE - Recife',
  '82': 'AL - Alagoas',
  '83': 'PB - Paraíba',
  '84': 'RN - Rio Grande do Norte',
  '85': 'CE - Fortaleza',
  '86': 'PI - Teresina',
  '87': 'PE - Interior',
  '88': 'CE - Interior',
  '89': 'PI - Interior',
  '91': 'PA - Belém',
  '92': 'AM - Manaus',
  '93': 'PA - Santarém',
  '94': 'PA - Marabá',
  '95': 'RR - Roraima',
  '96': 'AP - Amapá',
  '97': 'AM - Interior',
  '98': 'MA - São Luís',
  '99': 'MA - Interior',
}

export function estimarRegiaoPorTelefone(telefone?: string | null): string {
  if (!telefone) return 'Não identificado'
  const digitos = telefone.replace(/\D/g, '').replace(/^55/, '')
  const ddd = digitos.slice(0, 2)
  return DDD_REGIAO[ddd] || 'Não identificado'
}
