export const mockVehicles = [
  {
    id: '1',
    brand: 'Toyota',
    model: 'Corolla',
    version: '2.0 Altis Premium Hybrid',
    year: '2022/2023',
    km: 25000,
    price: 159900,
    type: 'próprio',
    images: [
      'https://img.usecurling.com/p/800/600?q=white%20sedan&color=white',
      'https://img.usecurling.com/p/800/600?q=car%20interior',
    ],
    transmission: 'Automático',
    fuel: 'Híbrido',
    doors: 4,
    color: 'Branco Pérola',
    plateEnd: '5',
    featured: true,
  },
  {
    id: '2',
    brand: 'Jeep',
    model: 'Compass',
    version: '1.3 T270 Longitude',
    year: '2021/2022',
    km: 42000,
    price: 135000,
    type: 'consignado',
    images: [
      'https://img.usecurling.com/p/800/600?q=suv&color=gray',
      'https://img.usecurling.com/p/800/600?q=suv%20interior',
    ],
    transmission: 'Automático',
    fuel: 'Flex',
    doors: 4,
    color: 'Cinza Granite',
    plateEnd: '8',
    featured: true,
  },
  {
    id: '3',
    brand: 'Honda',
    model: 'Hilux',
    version: '2.0 EXL',
    year: '2020/2020',
    km: 68000,
    price: 115000,
    type: 'próprio',
    images: [
      'https://img.usecurling.com/p/800/600?q=silver%20sedan&color=gray',
      'https://img.usecurling.com/p/800/600?q=car%20dashboard',
    ],
    transmission: 'Automático',
    fuel: 'Flex',
    doors: 4,
    color: 'Prata',
    plateEnd: '2',
    featured: true,
  },
  {
    id: '4',
    brand: 'Volkswagen',
    model: 'Nivus',
    version: '1.0 200 TSI Highline',
    year: '2023/2023',
    km: 12000,
    price: 128900,
    type: 'consignado',
    images: [
      'https://img.usecurling.com/p/800/600?q=red%20suv&color=red',
      'https://img.usecurling.com/p/800/600?q=modern%20car%20interior',
    ],
    transmission: 'Automático',
    fuel: 'Flex',
    doors: 4,
    color: 'Vermelho',
    plateEnd: '9',
    featured: true,
  },
  {
    id: '5',
    brand: 'Chevrolet',
    model: 'Polo',
    version: '1.0 TSI Comfortline',
    year: '2021/2022',
    km: 35000,
    price: 89900,
    type: 'próprio',
    images: ['https://img.usecurling.com/p/800/600?q=black%20hatchback&color=black'],
    transmission: 'Automático',
    fuel: 'Flex',
    doors: 4,
    color: 'Preto',
    plateEnd: '1',
    featured: true,
  },
  {
    id: '6',
    brand: 'Hyundai',
    model: 'HR-V',
    version: '1.0 TGDI Platinum',
    year: '2024/2024',
    km: 5000,
    price: 165000,
    type: 'consignado',
    images: ['https://img.usecurling.com/p/800/600?q=blue%20suv&color=blue'],
    transmission: 'Automático',
    fuel: 'Flex',
    doors: 4,
    color: 'Azul',
    plateEnd: '7',
    featured: true,
  },
]

export const mockTestimonials = [
  {
    id: 1,
    name: 'Carlos Henrique',
    text: 'Vendi meu carro em menos de uma semana através da consignação. Serviço transparente e muito seguro. Recomendo a Carro e Cia de olhos fechados!',
    role: 'Cliente Consignação',
  },
  {
    id: 2,
    name: 'Mariana Silva',
    text: 'Comprei meu primeiro SUV com eles. O atendimento do Roberto foi excepcional, tirou todas as minhas dúvidas e o carro estava impecável.',
    role: 'Cliente Compra',
  },
  {
    id: 3,
    name: 'Roberto Mendes',
    text: 'A melhor avaliação do mercado na troca do meu veículo. Confio no Luiz e na equipe há mais de 10 anos.',
    role: 'Cliente Fiel',
  },
]

export const mockTeam = [
  {
    name: 'Luiz Fernando',
    role: 'CEO & Fundador',
    img: 'https://img.usecurling.com/ppl/medium?gender=male&seed=1',
  },
  {
    name: 'Adriana Araújo',
    role: 'Gerente Comercial',
    img: 'https://img.usecurling.com/ppl/medium?gender=female&seed=2',
  },
  {
    name: 'Roberto Junior',
    role: 'Consultor de Vendas',
    img: 'https://img.usecurling.com/ppl/medium?gender=male&seed=3',
  },
  {
    name: 'Jessica Germano',
    role: 'Atendimento e Pós-venda',
    img: 'https://img.usecurling.com/ppl/medium?gender=female&seed=4',
  },
]

export const mockLeads = [
  {
    id: '1',
    name: 'João Paulo',
    phone: '(34) 99999-1111',
    interest: 'Jeep Compass',
    status: 'novo',
    date: '2023-10-25',
  },
  {
    id: '2',
    name: 'Maria Fernanda',
    phone: '(34) 98888-2222',
    interest: 'Consignação - Civic',
    status: 'em_atendimento',
    date: '2023-10-24',
  },
  {
    id: '3',
    name: 'Pedro Alves',
    phone: '(34) 97777-3333',
    interest: 'Toyota Corolla',
    status: 'negociacao',
    date: '2023-10-23',
  },
  {
    id: '4',
    name: 'Ana Costa',
    phone: '(34) 96666-4444',
    interest: 'Dúvida Financiamento',
    status: 'vendido',
    date: '2023-10-20',
  },
]
