-- Create the meta_webhook_logs table if it doesn't exist
CREATE TABLE IF NOT EXISTS public.meta_webhook_logs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT now(),
    platform text NOT NULL,
    event_type text,
    payload jsonb NOT NULL,
    processed boolean DEFAULT false,
    error text
);

-- Enable RLS
ALTER TABLE public.meta_webhook_logs ENABLE ROW LEVEL SECURITY;

-- Allow service role full access
DROP POLICY IF EXISTS "Service role full access on meta_webhook_logs" ON public.meta_webhook_logs;
CREATE POLICY "Service role full access on meta_webhook_logs" 
ON public.meta_webhook_logs 
FOR ALL TO service_role 
USING (true) WITH CHECK (true);

-- Create an index to quickly find unprocessed webhooks
CREATE INDEX IF NOT EXISTS idx_meta_webhook_logs_processed ON public.meta_webhook_logs (processed) WHERE processed = false;
