-- Artigo novo: esteira de postagens (aprovar um veículo por vez, Instagram + Facebook). 05/10/2026. Não duplica se rodar de novo.
INSERT INTO public.ajuda_conteudos (titulo, setor_id, categoria, caminho, o_que_e, para_que_serve, quando_utilizar, como_utilizar, dependencias)
SELECT
  'Esteira de postagens: aprovar um veículo por vez (Central de Redes Sociais)',
  '42cc009b-1f94-4bf1-bd2e-8b486f4c11fa'::uuid,
  'Marketing',
  'Menu lateral → Marketing → Central de Redes Sociais (/admin/central-social), aba "Aprovações"',
  'A esteira cria, um por vez, o post de carrossel de fotos de cada veículo disponível (Instagram e Facebook juntos) e mostra no topo da aba Aprovações para você aprovar ou pular. Os veículos vêm dos mais recentes no estoque para os mais antigos. Nada é publicado sem a sua aprovação.',
  'Divulgar todo o estoque nas redes sociais sem montar post por post, com você decidindo cada um.',
  'Quando quiser postar o estoque aos poucos. A esteira nasce pausada; ligue quando for começar.',
  E'1. Abra a Central de Redes Sociais, aba "Aprovações". No topo está o quadro "Esteira de postagens", com os contadores (concluídos, na fila, pulados, precisam de fotos).\n2. Clique em "Ligar esteira". O primeiro item aparece em seguida: veículo, tipo (carrossel de fotos) e os rascunhos do Instagram e do Facebook logo abaixo, nos cartões.\n3. Confira as fotos e a legenda nos cartões. Para mudar o texto ou tirar fotos, use "Editar" no cartão antes de aprovar. O selo verde "Fotos sem marca de IA" indica que o carrossel só tem fotos sem a marca d''água de IA.\n4. Clique em "Aprovar os dois": Instagram e Facebook são aprovados juntos e saem no próximo horário livre (por padrão 10h e 18h, horário de Brasília, 2 por dia por rede). A tela avisa o horário. Em seguida o próximo veículo já aparece.\n5. Se não quiser divulgar aquele veículo agora, clique em "Pular veículo": os rascunhos são apagados e o veículo não volta para a fila.\n6. "Pausar esteira" interrompe: nada novo é criado até ligar de novo. Os posts já aprovados continuam saindo nos horários marcados.\n7. Veículos com menos de 6 fotos sem marca de IA ficam em "Precisam de fotos novas" (veja a aba "Fotos" para reenviar as originais). Veículo vendido sai da fila sozinho; veículo novo entra na frente.\nObservações: a esteira cria um item por vez; se você não decidir, ela espera. A fila é conferida a cada 15 minutos e logo depois de cada aprovação. Vídeos ainda não entram na esteira (próxima etapa). Posts aprovados manualmente (fora da esteira) seguem saindo em até 15 minutos.',
  'Setor Marketing; veículos disponíveis com pelo menos 6 fotos sem marca de IA; conexão com Instagram e Facebook funcionando para publicar.'
WHERE NOT EXISTS (SELECT 1 FROM public.ajuda_conteudos WHERE titulo = 'Esteira de postagens: aprovar um veículo por vez (Central de Redes Sociais)');
