-- Central de Redes Sociais (04/10/2026): mensagens diretas e comentários ficam na Central, SEPARADOS do CRM de leads da Clara (que é só WhatsApp).
-- Reescreve os dois artigos (o de comentários dizia que virava lead; o de mensagens dizia que ia para o CRM).
UPDATE public.ajuda_conteudos
SET
  titulo = 'Responder comentários dos posts (Central de Redes Sociais)',
  caminho = 'Menu lateral → Marketing → Central de Redes Sociais (/admin/central-social), aba "Comentários"',
  o_que_e = 'A aba "Comentários" lista os comentários públicos dos posts e anúncios da página do Facebook e do perfil do Instagram, com opção de curtir e responder. Os que pedem preço ou mostram interesse de compra ganham o selo "Interesse de compra".',
  para_que_serve = 'Atender quem comenta sem entrar em cada rede, e não deixar sem resposta quem demonstrou interesse num carro. Comentário NÃO vira lead: o CRM de leads da Clara é só para o WhatsApp.',
  quando_utilizar = 'Ao acompanhar a movimentação das redes, ou quando chegar o aviso "Novo comentário com interesse" no WhatsApp.',
  como_utilizar = E'1. Abra a Central de Redes Sociais e clique em "Comentários". A lista carrega ao abrir a aba; para ver comentários novos, saia da aba e volte.\n2. Cada cartão mostra a rede, o nome de quem comentou, a data e o texto. O selo laranja "Interesse de compra" aparece quando o comentário pede valor, preço, troca, financiamento etc. Use o botão "Só com interesse de compra" no topo para ver só esses.\n3. Para curtir, clique em "Curtir". Para responder, escreva no campo "Escreva uma resposta..." e clique em "Responder"; quando já houver resposta, aparece "Respondido". Se a Meta recusar a ação, a tela mostra o motivo.\n4. Quando alguém comenta algo com interesse de compra, a responsável recebe um aviso no WhatsApp com o nome e o texto. O aviso é texto livre: a Meta só entrega se ela tiver falado com o número da empresa nas últimas 24 horas.\n5. Comentários feitos pela própria loja (respostas) não geram aviso. Comentários em anúncios também aparecem aqui.\nObservação: até 04/10/2026 os comentários do Instagram chegavam ao sistema mas eram descartados por um erro de formato; os guardados desde junho foram importados. Esta tela não oferece ocultar nem excluir comentário.',
  dependencias = 'Setor Marketing e a conexão com a Meta (webhook de comentários) funcionando.'
WHERE titulo = 'Responder comentários e transformar em lead (Central de Redes Sociais)';

UPDATE public.ajuda_conteudos
SET
  titulo = 'Responder mensagens diretas do Instagram e do Messenger (Central de Redes Sociais)',
  caminho = 'Menu lateral → Marketing → Central de Redes Sociais (/admin/central-social), aba "Mensagens"',
  o_que_e = 'A aba "Mensagens" reúne as conversas do direct do Instagram e do Messenger da página do Facebook: lista de conversas à esquerda, histórico e caixa de resposta à direita. É separada do CRM de leads da Clara, que é só para o WhatsApp.',
  para_que_serve = 'Não perder quem chama no direct ou no Messenger e responder sem sair do painel. Antes de 04/10/2026 essas mensagens chegavam ao sistema mas eram descartadas.',
  quando_utilizar = 'Sempre que aparecer o selo vermelho na aba "Mensagens" (mensagens de clientes sem resposta) ou chegar o aviso "Nova mensagem direta" no WhatsApp.',
  como_utilizar = E'1. Abra a Central de Redes Sociais e clique em "Mensagens". O número vermelho na aba é o total de mensagens de clientes ainda sem resposta.\n2. Escolha uma conversa na lista (Abertas, Resolvidas ou Todas). Ao abrir, as não lidas são zeradas. A tela atualiza sozinha a cada 20 segundos.\n3. Mensagens do cliente aparecem à esquerda; as da equipe, à direita. As que a equipe digitou direto no app do Instagram aparecem marcadas "pelo app". Foto, vídeo e áudio aparecem como "[enviou: foto]"; resposta a story aparece como "[Respondeu ao story]".\n4. Para responder, escreva na caixa e clique no botão de enviar (ou Ctrl+Enter). A Meta só permite responder até 24 horas depois da última mensagem do cliente: a tela mostra o tempo que resta e, depois disso, bloqueia o envio e pede para responder pelo app do Instagram ou do Facebook.\n5. Quando terminar o atendimento, clique em "Resolvida". Se o cliente escrever de novo, a conversa reabre sozinha.\n6. Cada mensagem nova de cliente também gera um aviso no WhatsApp da responsável (texto livre: a Meta só entrega se ela tiver falado com o número da empresa nas últimas 24 horas).\nAtenção: esta aba NÃO cria lead e a Clara (IA) não responde aqui. O nome do cliente vem do perfil quando a Meta permite; senão aparece "Cliente Instagram ···" com o final do identificador.',
  dependencias = 'Setor Marketing; conexão com a Meta com permissão de mensagens (Instagram e página) e o webhook funcionando. O Messenger do Facebook só aparece se a página estiver inscrita em mensagens.'
WHERE titulo = 'Mensagens diretas do Instagram e do Messenger no CRM';
